# Generated by Django 5.1 on 2024-11-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programa', '0002_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
    ]
